/*
  File autogenerated by gengetopt version 2.21
  generated with the following command:
  gengetopt --conf-parse --unamed-opts -i simulac.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: Simulac [options] outline_file maxtime printtime seed";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -V, --version              Print version and exit",
  "      --help                 print out help message and exit  (default=off)",
  "  -d, --debug=INT            set debugging level (0 = none, 1 = info, ... 5 = \n                               all)",
  "  -i, --init=STRING          initial condition, name=val (int)",
  "  -r, --rate=STRING          rate parameter, kNN=val (float)",
  "  -v, --volume=FLOAT         initial cell volume, (0-1]",
  "      --scale-init           scale initial conditions to match volume  \n                               (default=off)",
  "  -g, --growth=FLOAT         cell growth rate, (0-1]",
  "  -h, --header               print header row in output file  (default=on)",
  "  -m, --moi=INT              multiplicity of infection",
  "  -s, --single               single cell mode; turn off cell division  \n                               (default=off)",
  "  -p, --pops                 output transcription initiations  (default=off)",
  "      --matlab-setup=STRING  generate a MATLAB setup script",
  "      --python-setup=STRING  generate a MATLAB setup script",
  "  -P, --param=STRING         set parameter value",
  "  -C, --config-file=STRING   configuration file with additional options",
  "      --system-file=STRING   System description (outline file)",
  "      --config-path=STRING   Path to search for configuration files  \n                               (default=`.')",
  "      --maximum-time=DOUBLE  Maximum time to run the simulation  \n                               (default=`100')",
  "      --print-time=DOUBLE    Time interval to use for printing output state  \n                               (default=`1')",
  "      --seed=LONG            Seed for random number generator",
  "  -o, --output-file=STRING   Output file name",
  "  -l, --log-file=STRING      Log file name",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);
struct line_list
{
  char * string_arg;
  struct line_list * next;
};

static struct line_list *cmd_line_list = 0;
static struct line_list *cmd_line_list_tmp = 0;

static void
free_cmd_list(void)
{
  /* free the list of a previous call */
  if (cmd_line_list)
    {
      while (cmd_line_list) {
        cmd_line_list_tmp = cmd_line_list;
        cmd_line_list = cmd_line_list->next;
        free (cmd_line_list_tmp->string_arg);
        free (cmd_line_list_tmp);
      }
    }
}


struct string_list
{
  char * arg;
  char *orig;
  struct string_list * next;
};

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->version_given = 0 ;
  args_info->help_given = 0 ;
  args_info->debug_given = 0 ;
  args_info->init_given = 0 ;
  args_info->rate_given = 0 ;
  args_info->volume_given = 0 ;
  args_info->scale_init_given = 0 ;
  args_info->growth_given = 0 ;
  args_info->header_given = 0 ;
  args_info->moi_given = 0 ;
  args_info->single_given = 0 ;
  args_info->pops_given = 0 ;
  args_info->matlab_setup_given = 0 ;
  args_info->python_setup_given = 0 ;
  args_info->param_given = 0 ;
  args_info->config_file_given = 0 ;
  args_info->system_file_given = 0 ;
  args_info->config_path_given = 0 ;
  args_info->maximum_time_given = 0 ;
  args_info->print_time_given = 0 ;
  args_info->seed_given = 0 ;
  args_info->output_file_given = 0 ;
  args_info->log_file_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->help_flag = 0;
  args_info->debug_orig = NULL;
  args_info->init_arg = NULL;
  args_info->init_orig = NULL;
  args_info->rate_arg = NULL;
  args_info->rate_orig = NULL;
  args_info->volume_orig = NULL;
  args_info->scale_init_flag = 0;
  args_info->growth_orig = NULL;
  args_info->header_flag = 1;
  args_info->moi_orig = NULL;
  args_info->single_flag = 0;
  args_info->pops_flag = 0;
  args_info->matlab_setup_arg = NULL;
  args_info->matlab_setup_orig = NULL;
  args_info->python_setup_arg = NULL;
  args_info->python_setup_orig = NULL;
  args_info->param_arg = NULL;
  args_info->param_orig = NULL;
  args_info->config_file_arg = NULL;
  args_info->config_file_orig = NULL;
  args_info->system_file_arg = NULL;
  args_info->system_file_orig = NULL;
  args_info->config_path_arg = gengetopt_strdup (".");
  args_info->config_path_orig = NULL;
  args_info->maximum_time_arg = 100;
  args_info->maximum_time_orig = NULL;
  args_info->print_time_arg = 1;
  args_info->print_time_orig = NULL;
  args_info->seed_orig = NULL;
  args_info->output_file_arg = NULL;
  args_info->output_file_orig = NULL;
  args_info->log_file_arg = NULL;
  args_info->log_file_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->version_help = gengetopt_args_info_help[0] ;
  args_info->help_help = gengetopt_args_info_help[1] ;
  args_info->debug_help = gengetopt_args_info_help[2] ;
  args_info->init_help = gengetopt_args_info_help[3] ;
  args_info->init_min = -1;
  args_info->init_max = -1;
  args_info->rate_help = gengetopt_args_info_help[4] ;
  args_info->rate_min = -1;
  args_info->rate_max = -1;
  args_info->volume_help = gengetopt_args_info_help[5] ;
  args_info->scale_init_help = gengetopt_args_info_help[6] ;
  args_info->growth_help = gengetopt_args_info_help[7] ;
  args_info->header_help = gengetopt_args_info_help[8] ;
  args_info->moi_help = gengetopt_args_info_help[9] ;
  args_info->single_help = gengetopt_args_info_help[10] ;
  args_info->pops_help = gengetopt_args_info_help[11] ;
  args_info->matlab_setup_help = gengetopt_args_info_help[12] ;
  args_info->python_setup_help = gengetopt_args_info_help[13] ;
  args_info->param_help = gengetopt_args_info_help[14] ;
  args_info->param_min = -1;
  args_info->param_max = -1;
  args_info->config_file_help = gengetopt_args_info_help[15] ;
  args_info->system_file_help = gengetopt_args_info_help[16] ;
  args_info->config_path_help = gengetopt_args_info_help[17] ;
  args_info->maximum_time_help = gengetopt_args_info_help[18] ;
  args_info->print_time_help = gengetopt_args_info_help[19] ;
  args_info->seed_help = gengetopt_args_info_help[20] ;
  args_info->output_file_help = gengetopt_args_info_help[21] ;
  args_info->log_file_help = gengetopt_args_info_help[22] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);

  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

struct cmdline_parser_params *
cmdline_parser_params_init()
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));

  if (params)
    { 
      params->override = 0;
      params->initialize = 0;
      params->check_required = 0;
      params->check_ambiguity = 0;
    }
    
  return params;
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  unsigned int i;
  if (args_info->debug_orig)
    {
      free (args_info->debug_orig); /* free previous argument */
      args_info->debug_orig = 0;
    }
  if (args_info->init_arg)
    {
      for (i = 0; i < args_info->init_given; ++i)
        {
          if (args_info->init_arg [i])
            {
              free (args_info->init_arg [i]); /* free previous argument */
              args_info->init_arg [i] = 0;
            }
          if (args_info->init_orig [i])
            {
              free (args_info->init_orig [i]); /* free previous argument */
              args_info->init_orig [i] = 0;
            }
        }
      if (args_info->init_arg [0])
        free (args_info->init_arg [0]); /* free default string */
      free (args_info->init_arg); /* free previous argument */
      args_info->init_arg = 0;
      free (args_info->init_orig); /* free previous argument */
      args_info->init_orig = 0;
    }
  if (args_info->rate_arg)
    {
      for (i = 0; i < args_info->rate_given; ++i)
        {
          if (args_info->rate_arg [i])
            {
              free (args_info->rate_arg [i]); /* free previous argument */
              args_info->rate_arg [i] = 0;
            }
          if (args_info->rate_orig [i])
            {
              free (args_info->rate_orig [i]); /* free previous argument */
              args_info->rate_orig [i] = 0;
            }
        }
      if (args_info->rate_arg [0])
        free (args_info->rate_arg [0]); /* free default string */
      free (args_info->rate_arg); /* free previous argument */
      args_info->rate_arg = 0;
      free (args_info->rate_orig); /* free previous argument */
      args_info->rate_orig = 0;
    }
  if (args_info->volume_orig)
    {
      free (args_info->volume_orig); /* free previous argument */
      args_info->volume_orig = 0;
    }
  if (args_info->growth_orig)
    {
      free (args_info->growth_orig); /* free previous argument */
      args_info->growth_orig = 0;
    }
  if (args_info->moi_orig)
    {
      free (args_info->moi_orig); /* free previous argument */
      args_info->moi_orig = 0;
    }
  if (args_info->matlab_setup_arg)
    {
      free (args_info->matlab_setup_arg); /* free previous argument */
      args_info->matlab_setup_arg = 0;
    }
  if (args_info->matlab_setup_orig)
    {
      free (args_info->matlab_setup_orig); /* free previous argument */
      args_info->matlab_setup_orig = 0;
    }
  if (args_info->python_setup_arg)
    {
      free (args_info->python_setup_arg); /* free previous argument */
      args_info->python_setup_arg = 0;
    }
  if (args_info->python_setup_orig)
    {
      free (args_info->python_setup_orig); /* free previous argument */
      args_info->python_setup_orig = 0;
    }
  if (args_info->param_arg)
    {
      for (i = 0; i < args_info->param_given; ++i)
        {
          if (args_info->param_arg [i])
            {
              free (args_info->param_arg [i]); /* free previous argument */
              args_info->param_arg [i] = 0;
            }
          if (args_info->param_orig [i])
            {
              free (args_info->param_orig [i]); /* free previous argument */
              args_info->param_orig [i] = 0;
            }
        }
      if (args_info->param_arg [0])
        free (args_info->param_arg [0]); /* free default string */
      free (args_info->param_arg); /* free previous argument */
      args_info->param_arg = 0;
      free (args_info->param_orig); /* free previous argument */
      args_info->param_orig = 0;
    }
  if (args_info->config_file_arg)
    {
      free (args_info->config_file_arg); /* free previous argument */
      args_info->config_file_arg = 0;
    }
  if (args_info->config_file_orig)
    {
      free (args_info->config_file_orig); /* free previous argument */
      args_info->config_file_orig = 0;
    }
  if (args_info->system_file_arg)
    {
      free (args_info->system_file_arg); /* free previous argument */
      args_info->system_file_arg = 0;
    }
  if (args_info->system_file_orig)
    {
      free (args_info->system_file_orig); /* free previous argument */
      args_info->system_file_orig = 0;
    }
  if (args_info->config_path_arg)
    {
      free (args_info->config_path_arg); /* free previous argument */
      args_info->config_path_arg = 0;
    }
  if (args_info->config_path_orig)
    {
      free (args_info->config_path_orig); /* free previous argument */
      args_info->config_path_orig = 0;
    }
  if (args_info->maximum_time_orig)
    {
      free (args_info->maximum_time_orig); /* free previous argument */
      args_info->maximum_time_orig = 0;
    }
  if (args_info->print_time_orig)
    {
      free (args_info->print_time_orig); /* free previous argument */
      args_info->print_time_orig = 0;
    }
  if (args_info->seed_orig)
    {
      free (args_info->seed_orig); /* free previous argument */
      args_info->seed_orig = 0;
    }
  if (args_info->output_file_arg)
    {
      free (args_info->output_file_arg); /* free previous argument */
      args_info->output_file_arg = 0;
    }
  if (args_info->output_file_orig)
    {
      free (args_info->output_file_orig); /* free previous argument */
      args_info->output_file_orig = 0;
    }
  if (args_info->log_file_arg)
    {
      free (args_info->log_file_arg); /* free previous argument */
      args_info->log_file_arg = 0;
    }
  if (args_info->log_file_orig)
    {
      free (args_info->log_file_orig); /* free previous argument */
      args_info->log_file_orig = 0;
    }
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);
  
  if (args_info->inputs_num)
    free (args_info->inputs);
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->debug_given) {
    if (args_info->debug_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "debug", args_info->debug_orig);
    } else {
      fprintf(outfile, "%s\n", "debug");
    }
  }
  if (args_info->init_orig)
    {
      for (i = 0; i < args_info->init_given; ++i)
        {
          if (args_info->init_orig [i])
            {
              fprintf(outfile, "%s=\"%s\"\n", "init", args_info->init_orig [i]);
            }
        }
    }
  if (args_info->rate_orig)
    {
      for (i = 0; i < args_info->rate_given; ++i)
        {
          if (args_info->rate_orig [i])
            {
              fprintf(outfile, "%s=\"%s\"\n", "rate", args_info->rate_orig [i]);
            }
        }
    }
  if (args_info->volume_given) {
    if (args_info->volume_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "volume", args_info->volume_orig);
    } else {
      fprintf(outfile, "%s\n", "volume");
    }
  }
  if (args_info->scale_init_given) {
    fprintf(outfile, "%s\n", "scale-init");
  }
  if (args_info->growth_given) {
    if (args_info->growth_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "growth", args_info->growth_orig);
    } else {
      fprintf(outfile, "%s\n", "growth");
    }
  }
  if (args_info->header_given) {
    fprintf(outfile, "%s\n", "header");
  }
  if (args_info->moi_given) {
    if (args_info->moi_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "moi", args_info->moi_orig);
    } else {
      fprintf(outfile, "%s\n", "moi");
    }
  }
  if (args_info->single_given) {
    fprintf(outfile, "%s\n", "single");
  }
  if (args_info->pops_given) {
    fprintf(outfile, "%s\n", "pops");
  }
  if (args_info->matlab_setup_given) {
    if (args_info->matlab_setup_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "matlab-setup", args_info->matlab_setup_orig);
    } else {
      fprintf(outfile, "%s\n", "matlab-setup");
    }
  }
  if (args_info->python_setup_given) {
    if (args_info->python_setup_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "python-setup", args_info->python_setup_orig);
    } else {
      fprintf(outfile, "%s\n", "python-setup");
    }
  }
  if (args_info->param_orig)
    {
      for (i = 0; i < args_info->param_given; ++i)
        {
          if (args_info->param_orig [i])
            {
              fprintf(outfile, "%s=\"%s\"\n", "param", args_info->param_orig [i]);
            }
        }
    }
  if (args_info->config_file_given) {
    if (args_info->config_file_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "config-file", args_info->config_file_orig);
    } else {
      fprintf(outfile, "%s\n", "config-file");
    }
  }
  if (args_info->system_file_given) {
    if (args_info->system_file_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "system-file", args_info->system_file_orig);
    } else {
      fprintf(outfile, "%s\n", "system-file");
    }
  }
  if (args_info->config_path_given) {
    if (args_info->config_path_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "config-path", args_info->config_path_orig);
    } else {
      fprintf(outfile, "%s\n", "config-path");
    }
  }
  if (args_info->maximum_time_given) {
    if (args_info->maximum_time_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "maximum-time", args_info->maximum_time_orig);
    } else {
      fprintf(outfile, "%s\n", "maximum-time");
    }
  }
  if (args_info->print_time_given) {
    if (args_info->print_time_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "print-time", args_info->print_time_orig);
    } else {
      fprintf(outfile, "%s\n", "print-time");
    }
  }
  if (args_info->seed_given) {
    if (args_info->seed_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "seed", args_info->seed_orig);
    } else {
      fprintf(outfile, "%s\n", "seed");
    }
  }
  if (args_info->output_file_given) {
    if (args_info->output_file_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "output-file", args_info->output_file_orig);
    } else {
      fprintf(outfile, "%s\n", "output-file");
    }
  }
  if (args_info->log_file_given) {
    if (args_info->log_file_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "log-file", args_info->log_file_orig);
    } else {
      fprintf(outfile, "%s\n", "log-file");
    }
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  char *tok, *ret;
  size_t len, num_of_escape;
  int i, j;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static char *
get_multiple_arg_token_next(const char *arg)
{
  char *tok;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, int min, int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, int min, int max, const char *option_desc)
{
  int error = 0;

  if (option_given && ! (min < 0 && max < 0))
    {
      if (min >= 0 && max >= 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error = 1;
                }
            }
          else if (option_given < min
              || option_given > max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error = 1;
            }
        }
      else if (min >= 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error = 1;
            }
        }
      else if (max >= 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error = 1;
            }
        }
    }
    
  return error;
}
int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;

  result = cmdline_parser_internal (argc, argv, args_info, &params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->init_given, args_info->init_min, args_info->init_max, "'--init' ('-i')"))
     error = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->rate_given, args_info->rate_min, args_info->rate_max, "'--rate' ('-r')"))
     error = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->param_given, args_info->param_min, args_info->param_max, "'--param' ('-P')"))
     error = 1;
  
  
  /* checks for dependences among options */

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */
  char *multi_token, *multi_next; /* for multiple options */

  int i;        /* Counter */

  struct string_list * init_list = NULL,* init_new = NULL;
  struct string_list * rate_list = NULL,* rate_new = NULL;
  struct string_list * param_list = NULL,* param_new = NULL;
  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "version",	0, NULL, 'V' },
        { "help",	0, NULL, 0 },
        { "debug",	1, NULL, 'd' },
        { "init",	1, NULL, 'i' },
        { "rate",	1, NULL, 'r' },
        { "volume",	1, NULL, 'v' },
        { "scale-init",	0, NULL, 0 },
        { "growth",	1, NULL, 'g' },
        { "header",	0, NULL, 'h' },
        { "moi",	1, NULL, 'm' },
        { "single",	0, NULL, 's' },
        { "pops",	0, NULL, 'p' },
        { "matlab-setup",	1, NULL, 0 },
        { "python-setup",	1, NULL, 0 },
        { "param",	1, NULL, 'P' },
        { "config-file",	1, NULL, 'C' },
        { "system-file",	1, NULL, 0 },
        { "config-path",	1, NULL, 0 },
        { "maximum-time",	1, NULL, 0 },
        { "print-time",	1, NULL, 0 },
        { "seed",	1, NULL, 0 },
        { "output-file",	1, NULL, 'o' },
        { "log-file",	1, NULL, 'l' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "Vd:i:r:v:g:hm:spP:C:o:l:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'd':	/* set debugging level (0 = none, 1 = info, ... 5 = all).  */
          if (local_args_info.debug_given || (check_ambiguity && args_info->debug_given))
            {
              fprintf (stderr, "%s: `--debug' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->debug_given && ! override)
            continue;
          local_args_info.debug_given = 1;
          args_info->debug_given = 1;
          args_info->debug_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->debug_orig)
            free (args_info->debug_orig); /* free previous string */
          args_info->debug_orig = gengetopt_strdup (optarg);
          break;

        case 'i':	/* initial condition, name=val (int).  */
          local_args_info.init_given++;
        
          multi_token = get_multiple_arg_token(optarg);
          multi_next = get_multiple_arg_token_next (optarg);
        
          while (1)
            {
              init_new = (struct string_list *) malloc (sizeof (struct string_list));
              init_new->next = init_list;
              init_list = init_new;
              init_new->arg = gengetopt_strdup (multi_token);
              init_new->orig = multi_token;
        
              if (multi_next)
                {
                  multi_token = get_multiple_arg_token(multi_next);
                  multi_next = get_multiple_arg_token_next (multi_next);
                  local_args_info.init_given++;
                }
              else
                break;
            }
          break;

        case 'r':	/* rate parameter, kNN=val (float).  */
          local_args_info.rate_given++;
        
          multi_token = get_multiple_arg_token(optarg);
          multi_next = get_multiple_arg_token_next (optarg);
        
          while (1)
            {
              rate_new = (struct string_list *) malloc (sizeof (struct string_list));
              rate_new->next = rate_list;
              rate_list = rate_new;
              rate_new->arg = gengetopt_strdup (multi_token);
              rate_new->orig = multi_token;
        
              if (multi_next)
                {
                  multi_token = get_multiple_arg_token(multi_next);
                  multi_next = get_multiple_arg_token_next (multi_next);
                  local_args_info.rate_given++;
                }
              else
                break;
            }
          break;

        case 'v':	/* initial cell volume, (0-1].  */
          if (local_args_info.volume_given || (check_ambiguity && args_info->volume_given))
            {
              fprintf (stderr, "%s: `--volume' (`-v') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->volume_given && ! override)
            continue;
          local_args_info.volume_given = 1;
          args_info->volume_given = 1;
          args_info->volume_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->volume_orig)
            free (args_info->volume_orig); /* free previous string */
          args_info->volume_orig = gengetopt_strdup (optarg);
          break;

        case 'g':	/* cell growth rate, (0-1].  */
          if (local_args_info.growth_given || (check_ambiguity && args_info->growth_given))
            {
              fprintf (stderr, "%s: `--growth' (`-g') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->growth_given && ! override)
            continue;
          local_args_info.growth_given = 1;
          args_info->growth_given = 1;
          args_info->growth_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->growth_orig)
            free (args_info->growth_orig); /* free previous string */
          args_info->growth_orig = gengetopt_strdup (optarg);
          break;

        case 'h':	/* print header row in output file.  */
          if (local_args_info.header_given || (check_ambiguity && args_info->header_given))
            {
              fprintf (stderr, "%s: `--header' (`-h') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->header_given && ! override)
            continue;
          local_args_info.header_given = 1;
          args_info->header_given = 1;
          args_info->header_flag = !(args_info->header_flag);
          break;

        case 'm':	/* multiplicity of infection.  */
          if (local_args_info.moi_given || (check_ambiguity && args_info->moi_given))
            {
              fprintf (stderr, "%s: `--moi' (`-m') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->moi_given && ! override)
            continue;
          local_args_info.moi_given = 1;
          args_info->moi_given = 1;
          args_info->moi_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->moi_orig)
            free (args_info->moi_orig); /* free previous string */
          args_info->moi_orig = gengetopt_strdup (optarg);
          break;

        case 's':	/* single cell mode; turn off cell division.  */
          if (local_args_info.single_given || (check_ambiguity && args_info->single_given))
            {
              fprintf (stderr, "%s: `--single' (`-s') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->single_given && ! override)
            continue;
          local_args_info.single_given = 1;
          args_info->single_given = 1;
          args_info->single_flag = !(args_info->single_flag);
          break;

        case 'p':	/* output transcription initiations.  */
          if (local_args_info.pops_given || (check_ambiguity && args_info->pops_given))
            {
              fprintf (stderr, "%s: `--pops' (`-p') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->pops_given && ! override)
            continue;
          local_args_info.pops_given = 1;
          args_info->pops_given = 1;
          args_info->pops_flag = !(args_info->pops_flag);
          break;

        case 'P':	/* set parameter value.  */
          local_args_info.param_given++;
        
          multi_token = get_multiple_arg_token(optarg);
          multi_next = get_multiple_arg_token_next (optarg);
        
          while (1)
            {
              param_new = (struct string_list *) malloc (sizeof (struct string_list));
              param_new->next = param_list;
              param_list = param_new;
              param_new->arg = gengetopt_strdup (multi_token);
              param_new->orig = multi_token;
        
              if (multi_next)
                {
                  multi_token = get_multiple_arg_token(multi_next);
                  multi_next = get_multiple_arg_token_next (multi_next);
                  local_args_info.param_given++;
                }
              else
                break;
            }
          break;

        case 'C':	/* configuration file with additional options.  */
          if (local_args_info.config_file_given || (check_ambiguity && args_info->config_file_given))
            {
              fprintf (stderr, "%s: `--config-file' (`-C') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->config_file_given && ! override)
            continue;
          local_args_info.config_file_given = 1;
          args_info->config_file_given = 1;
          if (args_info->config_file_arg)
            free (args_info->config_file_arg); /* free previous string */
          args_info->config_file_arg = gengetopt_strdup (optarg);
          if (args_info->config_file_orig)
            free (args_info->config_file_orig); /* free previous string */
          args_info->config_file_orig = gengetopt_strdup (optarg);
          break;

        case 'o':	/* Output file name.  */
          if (local_args_info.output_file_given || (check_ambiguity && args_info->output_file_given))
            {
              fprintf (stderr, "%s: `--output-file' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->output_file_given && ! override)
            continue;
          local_args_info.output_file_given = 1;
          args_info->output_file_given = 1;
          if (args_info->output_file_arg)
            free (args_info->output_file_arg); /* free previous string */
          args_info->output_file_arg = gengetopt_strdup (optarg);
          if (args_info->output_file_orig)
            free (args_info->output_file_orig); /* free previous string */
          args_info->output_file_orig = gengetopt_strdup (optarg);
          break;

        case 'l':	/* Log file name.  */
          if (local_args_info.log_file_given || (check_ambiguity && args_info->log_file_given))
            {
              fprintf (stderr, "%s: `--log-file' (`-l') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->log_file_given && ! override)
            continue;
          local_args_info.log_file_given = 1;
          args_info->log_file_given = 1;
          if (args_info->log_file_arg)
            free (args_info->log_file_arg); /* free previous string */
          args_info->log_file_arg = gengetopt_strdup (optarg);
          if (args_info->log_file_orig)
            free (args_info->log_file_orig); /* free previous string */
          args_info->log_file_orig = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
          /* print out help message and exit.  */
          if (strcmp (long_options[option_index].name, "help") == 0)
          {
            if (local_args_info.help_given || (check_ambiguity && args_info->help_given))
              {
                fprintf (stderr, "%s: `--help' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->help_given && ! override)
              continue;
            local_args_info.help_given = 1;
            args_info->help_given = 1;
            args_info->help_flag = !(args_info->help_flag);
          }
          /* scale initial conditions to match volume.  */
          else if (strcmp (long_options[option_index].name, "scale-init") == 0)
          {
            if (local_args_info.scale_init_given || (check_ambiguity && args_info->scale_init_given))
              {
                fprintf (stderr, "%s: `--scale-init' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->scale_init_given && ! override)
              continue;
            local_args_info.scale_init_given = 1;
            args_info->scale_init_given = 1;
            args_info->scale_init_flag = !(args_info->scale_init_flag);
          }
          /* generate a MATLAB setup script.  */
          else if (strcmp (long_options[option_index].name, "matlab-setup") == 0)
          {
            if (local_args_info.matlab_setup_given || (check_ambiguity && args_info->matlab_setup_given))
              {
                fprintf (stderr, "%s: `--matlab-setup' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->matlab_setup_given && ! override)
              continue;
            local_args_info.matlab_setup_given = 1;
            args_info->matlab_setup_given = 1;
            if (args_info->matlab_setup_arg)
              free (args_info->matlab_setup_arg); /* free previous string */
            args_info->matlab_setup_arg = gengetopt_strdup (optarg);
            if (args_info->matlab_setup_orig)
              free (args_info->matlab_setup_orig); /* free previous string */
            args_info->matlab_setup_orig = gengetopt_strdup (optarg);
          }
          /* generate a MATLAB setup script.  */
          else if (strcmp (long_options[option_index].name, "python-setup") == 0)
          {
            if (local_args_info.python_setup_given || (check_ambiguity && args_info->python_setup_given))
              {
                fprintf (stderr, "%s: `--python-setup' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->python_setup_given && ! override)
              continue;
            local_args_info.python_setup_given = 1;
            args_info->python_setup_given = 1;
            if (args_info->python_setup_arg)
              free (args_info->python_setup_arg); /* free previous string */
            args_info->python_setup_arg = gengetopt_strdup (optarg);
            if (args_info->python_setup_orig)
              free (args_info->python_setup_orig); /* free previous string */
            args_info->python_setup_orig = gengetopt_strdup (optarg);
          }
          /* System description (outline file).  */
          else if (strcmp (long_options[option_index].name, "system-file") == 0)
          {
            if (local_args_info.system_file_given || (check_ambiguity && args_info->system_file_given))
              {
                fprintf (stderr, "%s: `--system-file' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->system_file_given && ! override)
              continue;
            local_args_info.system_file_given = 1;
            args_info->system_file_given = 1;
            if (args_info->system_file_arg)
              free (args_info->system_file_arg); /* free previous string */
            args_info->system_file_arg = gengetopt_strdup (optarg);
            if (args_info->system_file_orig)
              free (args_info->system_file_orig); /* free previous string */
            args_info->system_file_orig = gengetopt_strdup (optarg);
          }
          /* Path to search for configuration files.  */
          else if (strcmp (long_options[option_index].name, "config-path") == 0)
          {
            if (local_args_info.config_path_given || (check_ambiguity && args_info->config_path_given))
              {
                fprintf (stderr, "%s: `--config-path' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->config_path_given && ! override)
              continue;
            local_args_info.config_path_given = 1;
            args_info->config_path_given = 1;
            if (args_info->config_path_arg)
              free (args_info->config_path_arg); /* free previous string */
            args_info->config_path_arg = gengetopt_strdup (optarg);
            if (args_info->config_path_orig)
              free (args_info->config_path_orig); /* free previous string */
            args_info->config_path_orig = gengetopt_strdup (optarg);
          }
          /* Maximum time to run the simulation.  */
          else if (strcmp (long_options[option_index].name, "maximum-time") == 0)
          {
            if (local_args_info.maximum_time_given || (check_ambiguity && args_info->maximum_time_given))
              {
                fprintf (stderr, "%s: `--maximum-time' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->maximum_time_given && ! override)
              continue;
            local_args_info.maximum_time_given = 1;
            args_info->maximum_time_given = 1;
            args_info->maximum_time_arg = strtod (optarg, &stop_char);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->maximum_time_orig)
              free (args_info->maximum_time_orig); /* free previous string */
            args_info->maximum_time_orig = gengetopt_strdup (optarg);
          }
          /* Time interval to use for printing output state.  */
          else if (strcmp (long_options[option_index].name, "print-time") == 0)
          {
            if (local_args_info.print_time_given || (check_ambiguity && args_info->print_time_given))
              {
                fprintf (stderr, "%s: `--print-time' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->print_time_given && ! override)
              continue;
            local_args_info.print_time_given = 1;
            args_info->print_time_given = 1;
            args_info->print_time_arg = strtod (optarg, &stop_char);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->print_time_orig)
              free (args_info->print_time_orig); /* free previous string */
            args_info->print_time_orig = gengetopt_strdup (optarg);
          }
          /* Seed for random number generator.  */
          else if (strcmp (long_options[option_index].name, "seed") == 0)
          {
            if (local_args_info.seed_given || (check_ambiguity && args_info->seed_given))
              {
                fprintf (stderr, "%s: `--seed' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->seed_given && ! override)
              continue;
            local_args_info.seed_given = 1;
            args_info->seed_given = 1;
            args_info->seed_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->seed_orig)
              free (args_info->seed_orig); /* free previous string */
            args_info->seed_orig = gengetopt_strdup (optarg);
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  if (local_args_info.init_given && init_list)
    {
      struct string_list *tmp;
      args_info->init_arg = (char * *) realloc (args_info->init_arg, (args_info->init_given + local_args_info.init_given) * sizeof (char *));
      args_info->init_orig = (char **) realloc (args_info->init_orig, (args_info->init_given + local_args_info.init_given) * sizeof (char *));
      for (i = (local_args_info.init_given - 1); i >= 0; --i)
        {
          tmp = init_list;
          args_info->init_arg [i + args_info->init_given] = init_list->arg;
          args_info->init_orig [i + args_info->init_given] = init_list->orig;
          init_list = init_list->next;
          free (tmp);
        }
    }
  
  if (local_args_info.rate_given && rate_list)
    {
      struct string_list *tmp;
      args_info->rate_arg = (char * *) realloc (args_info->rate_arg, (args_info->rate_given + local_args_info.rate_given) * sizeof (char *));
      args_info->rate_orig = (char **) realloc (args_info->rate_orig, (args_info->rate_given + local_args_info.rate_given) * sizeof (char *));
      for (i = (local_args_info.rate_given - 1); i >= 0; --i)
        {
          tmp = rate_list;
          args_info->rate_arg [i + args_info->rate_given] = rate_list->arg;
          args_info->rate_orig [i + args_info->rate_given] = rate_list->orig;
          rate_list = rate_list->next;
          free (tmp);
        }
    }
  
  if (local_args_info.param_given && param_list)
    {
      struct string_list *tmp;
      args_info->param_arg = (char * *) realloc (args_info->param_arg, (args_info->param_given + local_args_info.param_given) * sizeof (char *));
      args_info->param_orig = (char **) realloc (args_info->param_orig, (args_info->param_given + local_args_info.param_given) * sizeof (char *));
      for (i = (local_args_info.param_given - 1); i >= 0; --i)
        {
          tmp = param_list;
          args_info->param_arg [i + args_info->param_given] = param_list->arg;
          args_info->param_orig [i + args_info->param_given] = param_list->orig;
          param_list = param_list->next;
          free (tmp);
        }
    }
  

  args_info->init_given += local_args_info.init_given;
  local_args_info.init_given = 0;
  args_info->rate_given += local_args_info.rate_given;
  local_args_info.rate_given = 0;
  args_info->param_given += local_args_info.param_given;
  local_args_info.param_given = 0;
  
  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  if (init_list)
    {
      struct string_list *tmp;
      while (init_list)
        {
          tmp = init_list;
          free (init_list->arg);
          free (init_list->orig);
          init_list = init_list->next;
          free (tmp);
        }
    }
  if (rate_list)
    {
      struct string_list *tmp;
      while (rate_list)
        {
          tmp = rate_list;
          free (rate_list->arg);
          free (rate_list->orig);
          rate_list = rate_list->next;
          free (tmp);
        }
    }
  if (param_list)
    {
      struct string_list *tmp;
      while (param_list)
        {
          tmp = param_list;
          free (param_list->arg);
          free (param_list->orig);
          param_list = param_list->next;
          free (tmp);
        }
    }
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}

#ifndef CONFIG_FILE_LINE_SIZE
#define CONFIG_FILE_LINE_SIZE 2048
#endif
#define ADDITIONAL_ERROR " in configuration file "

#define CONFIG_FILE_LINE_BUFFER_SIZE (CONFIG_FILE_LINE_SIZE+3)
/* 3 is for "--" and "=" */

static int
_cmdline_parser_configfile (char * const filename, int *my_argc)
{
  FILE* file;
  char my_argv[CONFIG_FILE_LINE_BUFFER_SIZE+1];
  char linebuf[CONFIG_FILE_LINE_SIZE];
  int line_num = 0;
  int result = 0, equal;
  char *fopt, *farg;
  char *str_index;
  size_t len, next_token;
  char delimiter;

  if ((file = fopen(filename, "r")) == NULL)
    {
      fprintf (stderr, "%s: Error opening configuration file '%s'\n",
               CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  while ((fgets(linebuf, CONFIG_FILE_LINE_SIZE, file)) != NULL)
    {
      ++line_num;
      my_argv[0] = '\0';
      len = strlen(linebuf);
      if (len > (CONFIG_FILE_LINE_BUFFER_SIZE-1))
        {
          fprintf (stderr, "%s:%s:%d: Line too long in configuration file\n",
                   CMDLINE_PARSER_PACKAGE, filename, line_num);
          result = EXIT_FAILURE;
          break;
        }

      /* find first non-whitespace character in the line */
      next_token = strspn (linebuf, " \t\r\n");
      str_index  = linebuf + next_token;

      if ( str_index[0] == '\0' || str_index[0] == '#')
        continue; /* empty line or comment line is skipped */

      fopt = str_index;

      /* truncate fopt at the end of the first non-valid character */
      next_token = strcspn (fopt, " \t\r\n=");

      if (fopt[next_token] == '\0') /* the line is over */
        {
          farg  = NULL;
          equal = 0;
          goto noarg;
        }

      /* remember if equal sign is present */
      equal = (fopt[next_token] == '=');
      fopt[next_token++] = '\0';

      /* advance pointers to the next token after the end of fopt */
      next_token += strspn (fopt + next_token, " \t\r\n");

      /* check for the presence of equal sign, and if so, skip it */
      if ( !equal )
        if ((equal = (fopt[next_token] == '=')))
          {
            next_token++;
            next_token += strspn (fopt + next_token, " \t\r\n");
          }
      str_index  += next_token;

      /* find argument */
      farg = str_index;
      if ( farg[0] == '\"' || farg[0] == '\'' )
        { /* quoted argument */
          str_index = strchr (++farg, str_index[0] ); /* skip opening quote */
          if (! str_index)
            {
              fprintf
                (stderr,
                 "%s:%s:%d: unterminated string in configuration file\n",
                 CMDLINE_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }
      else
        { /* read up the remaining part up to a delimiter */
          next_token = strcspn (farg, " \t\r\n#\'\"");
          str_index += next_token;
        }

      /* truncate farg at the delimiter and store it for further check */
      delimiter = *str_index, *str_index++ = '\0';

      /* everything but comment is illegal at the end of line */
      if (delimiter != '\0' && delimiter != '#')
        {
          str_index += strspn(str_index, " \t\r\n");
          if (*str_index != '\0' && *str_index != '#')
            {
              fprintf
                (stderr,
                 "%s:%s:%d: malformed string in configuration file\n",
                 CMDLINE_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }

    noarg:
      if (!strcmp(fopt,"include")) {
        if (farg && *farg) {
          result = _cmdline_parser_configfile(farg, my_argc);
        } else {
          fprintf(stderr, "%s:%s:%d: include requires a filename argument.\n",
                  CMDLINE_PARSER_PACKAGE, filename, line_num);
        }
        continue;
      }
      len = strlen(fopt);
      strcat (my_argv, len > 1 ? "--" : "-");
      strcat (my_argv, fopt);
      if (len > 1 && ((farg && *farg) || equal))
        strcat (my_argv, "=");
      if (farg && *farg)
        strcat (my_argv, farg);
      ++(*my_argc);

      cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
      cmd_line_list_tmp->next = cmd_line_list;
      cmd_line_list = cmd_line_list_tmp;
      cmd_line_list->string_arg = gengetopt_strdup(my_argv);
    } /* while */

  if (file)
    fclose(file);
  return result;
}

int
cmdline_parser_configfile (char * const filename,
                           struct gengetopt_args_info *args_info,
                           int override, int initialize, int check_required)
{
  struct cmdline_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  
  return cmdline_parser_config_file (filename, args_info, &params);
}

int
cmdline_parser_config_file (char * const filename,
                           struct gengetopt_args_info *args_info,
                           struct cmdline_parser_params *params)
{
  int i, result;
  int my_argc = 1;
  char **my_argv_arg;
  char *additional_error;

  /* store the program name */
  cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
  cmd_line_list_tmp->next = cmd_line_list;
  cmd_line_list = cmd_line_list_tmp;
  cmd_line_list->string_arg = gengetopt_strdup (CMDLINE_PARSER_PACKAGE);

  result = _cmdline_parser_configfile(filename, &my_argc);

  if (result != EXIT_FAILURE) {
    my_argv_arg = (char **) malloc((my_argc+1) * sizeof(char *));
    cmd_line_list_tmp = cmd_line_list;

    for (i = my_argc - 1; i >= 0; --i) {
      my_argv_arg[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

    my_argv_arg[my_argc] = 0;

    additional_error = (char *)malloc(strlen(filename) + strlen(ADDITIONAL_ERROR) + 1);
    strcpy (additional_error, ADDITIONAL_ERROR);
    strcat (additional_error, filename);
    result =
      cmdline_parser_internal (my_argc, my_argv_arg, args_info,
                              params,
                              additional_error);

    free (additional_error);
    free (my_argv_arg);
  }

  free_cmd_list();
  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}
